import express from "express";
import { addToCart, applyCoupon, clearCart, getCart, removeCartItem, updateCartItem } from "../controllers/cartController.js";
import { protect } from "../middleware/authMiddleware.js";
const router = express.Router();
router.use(protect);
router.get("/", getCart);
router.post("/add", addToCart);
router.post("/apply-coupon", applyCoupon);
router.patch("/:itemId", updateCartItem);
router.delete("/:itemId", removeCartItem);
router.delete("/clear", clearCart);
export default router;
